EOI EQU 20H
IMR EQU 21H
INT2 EQU 26H ;DIRECCION HANDSHAKE
HAND_DATOS EQU 40H
HAND_ESTADO EQU 41H ;REGISTROS HANDSHAKE

ORG 1000H
	MSJ DB "LOS CAPITOS IMPRIMEN POR HANDSHAKE"
	FIN DB ?
ORG 3000H
	; 1) SUBRUTINA QUE ATIENDE LA INTERRUPCION
	;-----------------------------------------
	SUB_INT2: MOV AL, [BX]
						OUT HAND_DATOS, AL
						INC BX
						;LE AVISAMOS AL PIC QUE SE ATENDIO SU INTERRUPCION
						MOV AL, 20H
						OUT EOI, AL
	IRET
ORG 2000H
	;2) ELEGIR UN ID Y GUARDAMOA LA DIRECCION DE LA SUBRUTINA
  ;EN EL VECTOR DE INTERRUPCIONES ID = 10
	;--------------------------------------------------------
	MOV AX, SUB_INT2
	MOV BX, 40
	MOV [BX], AX ; EN 40H = 3000H
	
	;3) CONFIGURAMOS EL PIC
	;----------------------
	CLI
		MOV AL, 11111011B ;SOLO HABILITAMOS LA INT2
		OUT IMR, AL
		
		MOV AL, 10
		OUT INT2, AL ;INT2 AHORA SABE QUE SU ID = 10
	STI
	
	MOV BX, OFFSET MSJ
	
	;4) CONFIGURAMOS HANDSHAKE POR INTERRUPCION
	;------------------------------------------
	IN AL, HAND_ESTADO
	OR AL, 10000000B ;FORZAMOS BIT 7 A 1
	OUT HAND_ESTADO, AL
	
	;5) MANDAMOS STRING
	;------------------
	LOOP: CMP BX, OFFSET FIN
				JNZ LOOP
	
	;6) DESACTIVAR LA INTERRUPCION
	;-----------------------------
	IN AL, HAND_ESTADO
	AND AL, 01111111B ;FORZAMOS BIT 7 A 0
	OUT HAND_ESTADO, AL
INT 0
END