;14) * Implementar un reloj similar al utilizado en los partidos de básquet, que arranque
; y detenga su marcha al presionar
;sucesivas veces la tecla F10 y que finalice el conteo al alcanzar los 30 segundos.
EOI EQU 20H
IMR EQU 21H
INT0 EQU 24H
INT1 EQU 25H
CONT EQU 10H ;CONTADOR DEL TIMER
COMP EQU 11H ;COMPARADOR DEL TIMER

ORG 4000H
 TIMER: INC UNIDAD
  CMP UNIDAD, 3AH
  JNZ IMPRIMIR
  MOV UNIDAD,30H
  INC DECENA
  CMP DECENA, 33H
  JNZ IMPRIMIR
  MOV DECENA, 30H
  
  ;DESHABILITAMOS TIMER SI LLEGO A 30 Y NO REINICIAMOS
  MOV AL, 11111101B
  OUT IMR, AL
  JMP CHAU
  
  IMPRIMIR: MOV AL, OFFSET FIN - OFFSET DECENA
  INT 7
  ;RESETEAMOS CONTADOR
  MOV AL, 0
  OUT CONT, AL
  
  ;AVISAMOS AL PIC QUE ATENDIMOS LA INT
  MOV AL, 20H
  OUT EOI, AL
 CHAU: IRET

ORG 3000H
 F10: IN AL, IMR ;DESHABILITAMOS Y HABILITAMOS TIMER
  XOR AL, 00000010B
  OUT IMR, AL
  
  MOV AL, 20H
  OUT EOI, AL
 IRET
  
ORG  1000H
 DECENA DB 30H
 UNIDAD DB 30H
 DB 13
 FIN DB ?
 
ORG 2000H
 ;VECTOR DE INTERRUPCIONES
 ;------------------------
 MOV AX, TIMER ;CARGAMOS TIMER
 MOV BX, 80
 MOV [BX],AX
 
 MOV AX, F10 ;CARGAMOS F10
 MOV BX, 40
 MOV [BX], AX
 
 ;CONFIGURAMOS PIC
 ;----------------
 CLI
  MOV AL, 11111110B
  OUT IMR, AL
  
  MOV AL, 10
  OUT INT0, AL
  
  MOV AL, 20
  OUT INT1, AL
  
  ;TIMER
  ;-----
  MOV AL, 0
  OUT CONT, AL
  
  MOV AL,1
  OUT COMP, AL
 STI
 
 MOV BX, OFFSET DECENA
 
 LAZO: JMP LAZO
 
INT 0
END
 
 