EOI EQU 20H
IMR EQU 21H		;DECLARACION DE CONSTANTES PARA MEJORAR LA LEGIBILDAD
INT1 EQU 25H ;DIRECCION DEL TIMER

;REGISTROS DEL TIMER
CONT EQU 10H
COMP EQU 11H

ORG 1000H
	MENSAJE DB " [GRETA LA MAS CAPA ] "
	FIN DB ?
	
ORG 3000H
	;SUBRUTINA DE MANEJO DE INTERRUPCION
	;-----------------------------------
	LETRERO: MOV BX, OFFSET MENSAJE
					 MOV AL, OFFSET FIN - OFFSET MENSAJE
					 INT 7
		;RESETEAMOS CONTADOR PARA QUE SE SIGA REPITIENDO
		;-----------------------------------------------
					 MOV AL,0
				   OUT CONT, AL
		;AVISAMOS AL PIC QUE SE ATEDIO LA INTERRUPCION
		;--------------------------------------
				   MOV AL, 20H
		       OUT EOI, AL
	IRET
ORG 2000H
	; CONFIGURAMOS EL VECTOR DE INTERRUPCIONES
	;-----------------------------------------
	MOV AX, LETRERO
	MOV BX, 40
	MOV [BX],AX ;LE MANDAMOS EL 3000H AL VECTOR POS 10 (10*4=40)
	;CONFIGURACION DEL PIC
	;---------------------
	CLI
		;HABILITAMOS LA INT1
		MOV AL, 11111101B
		OUT IMR,AL ;21H=11111101B
		
		;CONFIGURAMOS EL ID
		MOV AL, 10
		OUT INT1,AL
		
		;CONFIGURAR SECUENCIA DEL TIMER
		MOV AL, 0
		OUT CONT, AL
		
		MOV AL, 2
		OUT COMP, AL
	STI
	
	;CREAMOS UN LOOP PARA VER
	LOOP: JMP LOOP
INT 0
END
	