;a) * Escribir un programa para imprimir la letra “A” utilizando la impresora a través de la PIO.

PA EQU 30H ;ESTADO
PB EQU 31H ;DATOS
CA EQU 31H
CB EQU 33H

ORG 1000H
	LETRA DB " A "

ORG 2000H
	;CONFIGURAR PIO
	;--------------
		;DESHABILITAMOS EL STROBE
		MOV AL, 11111101B
		OUT CA, AL
		
		;PB COMO SALIDA
		MOV AL, 00000000B
		OUT CB, AL
		
	;RECORRER STRING
	MOV BX, OFFSET LETRA
		
	;CONSULTA DE ESTADO
	POLL: IN AL, PA
	AND AL, 00000001B
	JNZ POLL
	
	;MANDAMOS CARACTER
	
	MOV AL, [BX]
	OUT PB, AL
	
	;HABILITAMOS STROBE
	IN AL, PA
	OR AL, 00000010B
	
	;DESHABILITAMOS STROBE
	
	IN AL, PA
	AND AL, 11111101B
	OUT PA, AL
INT 0
END