;b) * Escribir un programa para imprimir el mensaje “ORGANIZACION Y ARQUITECTURA DE
;COMPUTADORAS” utilizando la impresora a través de la PIO.
PA EQU 30H ;ESTADO
PB EQU 31H ;DATOS
CA EQU 32H
CB EQU 33H

ORG 1000H
 LETRA DB "ORGANIZACION Y ARQUITECTURA DE COMPUTADORAS"
 FIN DB ?
 
ORG 2000H
 ;1) CONFIGURACION DEL PIO
 ;---------------------
 
 ;PA COMO ESTADO
 MOV AL, 11111101B ; STROBE = 0, BUSY = 1
 OUT CA, AL
 
 ;PB COMO DATOS
 MOV AL, 000000000B ;PB COMO SALIDA
 OUT CB, AL
 
 ;2) ENVIAMOS STRING
 ;------------------
 MOV BX, OFFSET LETRA
 
 
 ;3) POLL
 ;-------
  POLL: IN AL, PA ;NOS GUARDAMOS EL ESTADO
  AND AL, 00000001B ;CHEQUEAMOS EL ESTADO DEL BUSY
  JNZ POLL
  
 ;LE MANDAMMOS EL CARACTER SI ESTA LIBRE
 MOV AL, [BX]
 OUT PB, AL
 
 IN AL, PA
 OR AL, 00000010B ;FORZAMOS STROBE PARA QUE IMPRIMA
 OUT PA, AL
 
 ;DESHABILITAMOS STROBE Y REINICIAMOS
 IN AL, PA
 AND AL, 11111101B
 OUT PA, AL
 
 INC BX
 CMP BX, OFFSET FIN
 JNZ POLL
 
INT 0
END
 
 